version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_started
    entrypoint: "java -jar /api/api.jar"
    networks:
      - api-net
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/settings:/etc/mysql/conf.d/
      - ./mysql/data/:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: mdr_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - api-net
networks:
  api-net:
    driver: bridge
